### ISSUE TITLE
Run pipeline on biowulf - Memory issue 

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#209]
no problem with installation and preflight.

error occured when run 'cgr submit':

sbatch: error: Invalid --mem specification

**Comment by dorks81** [comment]
The wrapper for biowulf does not provide a default memory setting so --local-mem-mb needs to be specified in the command line execution.
```cgr submit --biowulf --local-mem-mb 8000```
