### ISSUE TITLE
discordant expected duplicate removal

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#210]
discordant expected duplicate removal not properly removed

**Comment by ngaddis** [comment]
Currently removes just lower call rate one - both should be removed if discordant.

**Comment by kliao12** [comment]
Completed. [commit](https://github.com/NCI-CGR/GwasQcPipeline/commit/98647c688952d223faa7d5795e2d56411c9f1474)

**Comment by jaamarks** [comment]
Opening this issue back up because of the following statement:

> I recently run a qc using v1.4.0 and we still see an issue with discordant expected replicates not removed.

**Comment by 1teaspoon** [comment]
![Screenshot (602)](https://github.com/user-attachments/assets/95fbcd39-bfda-476d-8d78-2d3376a29d10)
![Screenshot (603)](https://github.com/user-attachments/assets/17fcae0d-7997-4495-ba78-03c473c4e209)
![Screenshot (604)](https://github.com/user-attachments/assets/68189ece-8850-4303-aa32-363ea46de840)

**Comment by jaamarks** [comment]
Thanks @1teaspoon. Reviewing the screenshots, it seems we need an additional step. While @kliao12 correctly implemented the logic to flag a sample as `is_discordant_replicate=TRUE` when Plink, Graf, and King data are missing, we should also set `Sample Used in Subject Analysis` to `FALSE` for these samples.
