### ISSUE TITLE
required output file .nosex 

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#214]
when plink .fam file has sex phenotype, .nosex is not generated which causes an error because .nosex is always expected as an output

**Comment by shukwong** [comment]
remove the expectation of .nosex information when plink files are used as input files, will provide test dataset

**Comment by ngaddis** [comment]
Either correct at each step that uses plink or remove sex at beginning and add back at the end or add touch command.

**Comment by carynwillis** [comment]
This issue was fixed for all plink steps with #356.
