### ISSUE TITLE
ancestry triangle plot bug

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#216]
Ancestry triangle plot is empty when running some dataset.

**Comment by shukwong** [comment]
only happen in 2 external datasets, will provide the test data...

**Comment by kliao12** [comment]
Fixed. Problem occurs in datasets when sample names are numeric rather than character. Commit: [bbcdad8](https://github.com/NCI-CGR/GwasQcPipeline/commit/bbcdad8a94a6608e828a8ef946ab14f6efbc0947)
