### ISSUE TITLE
sorting IBD tabs and family tabs in the delivery qc table

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#218]
sort by PIHAT value in the IBD tab; sort by family id in the family tab

**Comment by shukwong** [comment]
sort by family id first, then within each family, sort by PIHAT in descending order

**Comment by carynwillis** [comment]
@shukwong @1teaspoon Could you please clarify what you mean by sort by family then by PIHAT. I see that the FAMILY tabs have FAM_ID and Subject_ID. So, I sorted by ascending FAM_ID. For the IBD tab, there is no FAM_ID column, so I just sorted by descending PLINK_PI_HAT. Should FAM_ID be added and sorted by FAM_ID then PLINK_PI_HAT? Thanks.

**Comment by 1teaspoon** [comment]
@carynwillis Hi Caryn I think what your done is what we need :). We just need FAMILY tabs sorted by FAM_ID and IBD tab sorted by PI_HAT. Thank you!

**Comment by carynwillis** [comment]
Fixed and merged to default with commit [fcec269](https://github.com/NCI-CGR/GwasQcPipeline/commit/fcec269aff3ca6e6591fb6cdbd736b816bdd6f3e) / PR #270.
