### ISSUE TITLE
sex plot - no sex information

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#220]

**Comment by 1teaspoon** [comment]
the pipeline cannot do sex plot when no expected sex info (when expected sex is set to ‘U’) – we should change the script to generate sex plot like even no expected sex or identifier sex

**Comment by dorks81** [comment]
Updated pipeline to create sex plot for 'U' category. Add sex_chr_included: flag to config.yaml file
