### ISSUE TITLE
Cannot run cgr command on GCP after installation on 3/11/2022

### ISSUE THREAD

**Issue by FrederickDong** [NCI-CGR/GwasQcPipeline#223]
After a fresh install on a Slurm cluster in GCP, the pipeline no longer executes. Specifically, "cgr --help" leads to the following error: ImportError: cannot import name 'soft_unicode' from 'markupsafe'

markupsafe.__version__ from the pipeline conda environment indicates that version 2.1.0 is installed. Others have [reported](https://github.com/aws/aws-sam-cli/issues/3661) encountering this error in this new version of markupsafe 2.1.0. The recommended solution appears to be to downgrade the package.

**Comment by FrederickDong** [comment]
Previous working version installed 2.0.1. This is also a version suggested in the thread linked above

**Comment by vthovarai** [comment]
Confirming workaround solution is to downgrade markupsafe to 2.0.2
After installing GwasQcPipeline environment, install older markupsafe using the following command.
pip install markupsafe==2.0.1
This allows "cgr --help" to run as expected
