### ISSUE TITLE
Snakemake version

### ISSUE THREAD

**Issue by FrederickDong** [NCI-CGR/GwasQcPipeline#225]
Snakemake version in production version of pipeline appears to change unpredictably (6.12 in GCP, 6.15.5 on Biowulf), despite being specified in the lock file as 6.4.1. 
Dev version installs 6.4.1 but encounters errors that are resolved by downgrading to 6.15.5.

**Comment by FrederickDong** [comment]
pyproject.toml has been updated. Snakemake changed to a tilde dependency with version specified as 6.15.5. This is confirmed to run on Biowulf. 

Will confirm output and test run on GCP.

**Comment by dorks81** [comment]
Confirmed on Biowulf
