### ISSUE TITLE
Need updates/improvements for "Sample_QC" sheet of the QC summary excel file

### ISSUE THREAD

**Issue by liuj1818** [NCI-CGR/GwasQcPipeline#227]
In Sample_QC file (in the delivery folder and files_for_lab folder), the “expected dups” and “unexpected dups” flag columns are missing. This two columns were in the legacy QC pipeline and are used to populate the LIMS system. These information should be there.

**Comment by 1teaspoon** [comment]
Just to clarify the columns want to add are "Expected Replicate Discordance" and "Unexpected Replicate", same as the last two columns in LIMS_Upload file in files_for_lab folder

**Comment by carynwillis** [comment]
Completed with PR #275.
