### ISSUE TITLE
LIMS upload function needs to be tested

### ISSUE THREAD

**Issue by liuj1818** [NCI-CGR/GwasQcPipeline#228]
Files under "files_for_lab" are designed to be used for populating LIMS system with QC results. This function should be tested more thoroughly.

**Comment by 1teaspoon** [comment]
we want the lims upload function is active by default, and also have an option to turn off the upload function

**Comment by ngaddis** [comment]
Function has been added to new QC pipeline, but has not been tested. Want to fully automate process of transferring QC pipeline results to LIMS system.

**Comment by carynwillis** [comment]
Completed with PR #275.
