### ISSUE TITLE
Please look into dependabot critical issues

### ISSUE THREAD

**Issue by shukwong** [NCI-CGR/GwasQcPipeline#233]
Currently, the dependabot has critical issues on the security of the Pillow package. Please look into it and see if we need to upgrade the package
https://github.com/NCI-CGR/GwasQcPipeline/security/dependabot

**Comment by DMH-BAH** [comment]
Bumped pillow from 8.4.0 to 9.0.1 after Dependabot flagged the older version as a risk.  Still need to test this new updated version before committing

**Comment by dorks81** [comment]
Verified Pillow version 9.2.0 is loaded in environment and no error messages during run
