### ISSUE TITLE
Unknow samples missing in the triangle plot (Figure 3) 

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#237]
the samples that have case/control status as 'Unknown/blank' should be included when generating the triangle plot (Figure 3)

**Comment by kliao12** [comment]
QC requested to also be included in triangle plot. Only include project QC rather than internal QC. Change to use subject level file (instead of sample level) which only retains project QC. Also ensure colors are consistent across plots
