### ISSUE TITLE
modify text in template doc Section 4.5 Subject Relateness

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#239]
We want to add the following words to the beginning of sentence:

"A total of x subjects were found to be related at the 1st or 2nd degree level. These subjects can be split into x families. "

**Comment by kliao12** [comment]
Confirmed with Jiahui and Jia on 02/27/24 via teams that this issue has already been resolved

**Comment by kliao12** [comment]
Closed
