### ISSUE TITLE
Summary table 4a/4b:  Unknown samples not counted

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#240]
Summary table 4a/4b when there are samples with Case/Control status = 'U', these samples are not counted in the table.

**Comment by 1teaspoon** [comment]
When Case/Control_status =' ' or 'Unknown', these sample counts should be reflected in the 'Other' column in 4a/4b

**Comment by ngaddis** [comment]
Summary table is in output Word document. Empty case/control status treated as unknown.
