### ISSUE TITLE
Lims_Upload file header and low call rate column of samples missing gtcs not correct

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#243]
should replace 'Sample_ID' and 'Call_Rate_Initial' with 'Sample ID' and 'Call Rate'

**Comment by 1teaspoon** [comment]
For the samples missing GTC files, their status in the low call rate column should be TRUE instead of blank

**Comment by carynwillis** [comment]
Fixed as of Feb 14, 2024 (commit 029a3c7).
