### ISSUE TITLE
new graf-pop software implementation

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#246]

**Comment by 1teaspoon** [comment]
the pipeline is using graf -pop from  [https://github.com/ncbi/graf]

Below is the detailed version info:

package:
  name: graf
  version: "12sep2018"
source:
  url: [https://github.com/ncbi/graf/archive/master.zip]
The documentation is from [https://github.com/NCI-CGR/conda-cgr/blob/default/recipes/graf/meta.yaml]

we want to update the pipeline to use the 'real' graf-pop https://pubmed.ncbi.nlm.nih.gov/31151998/

**Comment by dorks81** [comment]
Graf 2.4 is available via a download but not as a URL for conda-cgr. The GRAF repo team needs to release v2.4 to the URL used by conda-cgr. GRAF repo already has a ticket for this issue.

**Comment by ngaddis** [comment]
Update in relatedness module as well

**Comment by kliao12** [comment]
Completed as of v1.3.0

**Comment by kliao12** [comment]
Completed as of v1.3.0
