### ISSUE TITLE
CI/CD for Automated Documentation Updates with Latest Software Version Tag

### ISSUE THREAD

**Issue by jaamarks** [NCI-CGR/GwasQcPipeline#264]
#### Overview
Currently, whenever we release a new version of the software, we need to manually create a separate commit to update the installation instructions in the documentation. This can be time-consuming and prone to errors, especially as the project grows.

#### Proposed solution
Implement some mechanism to automatically update the installation instructions with the latest software version during the CI/CD pipeline. Maybe leverage an environmental variable that will store the latest version tag and incorporate that into the docs.

**Comment by kliao12** [comment]
Fixed with PR #278
