### ISSUE TITLE
Unexpected Replicate count/flag when one of the pair is contaminated

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#269]
In situation when one of the unexpected dup pair is contaminated (so that the subject is removed from subject level qc ), we want to fix the pipeline so that the other pair of the unexpected dup should not be counted as 'Unexpected Replicate'. 

Two things related to this issue and need to be fixed: 1) column D in Subject_QC tab in excel summary file (delivery folder) 2) Table 4b "Unexpected Replicates" row count in the QC report (delivery folder)

More details can be explored in the LM 7a qc run.

**Comment by jaamarks** [comment]
## Proposal for Improved Handling of Unexpected Replicates

### Issue

The current approach for handling unexpected replicates is insufficient. It indiscriminately flags and discards samples initially reported as distinct subjects in the `cgr_sample_sheet.csv` but subsequently identified as replicates through concordance checks. However, there are instances where we would like to retain one sample and discard the other, such as when one sample is contaminated. This would allow us to preserve the subject using the uncontaminated sample.

Below, we outline a new approach that will allow us to retain uncontaminated samples. Specifically, when encountering unexpected replicates where one is contaminated and the other is not, this approach will enable us to retain the uncontaminated sample while discarding the contaminated one.

### Proposed Solution
1. **Expand Unexpected Replicate Categorization** 
Currently, the "Unexpected Replicate" field is limited to a binary (True/False) value, which hinders our ability to capture nuanced information about replicate relationships. To address this, we propose introducing an integer-based "Unexpected Replicate Status" field. This field would provide a more granular classification of replicate status, including information about contamination and retention. 
 
**Proposed "Unexpected Replicate Status" Values:**
- 0: Not an unexpected replicate
- 1: Retained unexpected replicate (only the other sample is contaminated)
- 2: Not retained unexpected replicate (this sample is contaminated)
- 3: Not retained unexpected replicate (neither sample is contaminated)

<br>
The following is a screenshot of the terminal's stdout which showcases the logic of this new approach:
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/ac173216-9a0e-4c55-b743-95e31807864b">


<br><br>

Alternatively, we could simplify the scale to:

- 0: Not an unexpected replicate
- 1: Retained unexpected replicate
- 2: Not retained unexpected replicate

<br>

**Reporting**
- **`QC_Report.xlsx` (SUBJECT_QC sheet)**: Replace the boolean "Unexpected Replicates" Field with the new integer-based  "Unexpected Replicate Status" field.
- The "Unexpected Replicates" row in Table 4b of the `QC_Report.docx` will be modified to display only the count of unexpected replicates not retained and we will include a description of this for the table.

<br><br>

2. **Create a Data Dictionary for `QC_Report.xlsx`** 
To improve data clarity and consistency, we propose adding a "SUBJECT QC Data Dictionary" sheet to the `QC_Report.xlsx`. This sheet will provide detailed descriptions of each column in the SUBJECT_QC sheet.  Below is a screenshot of what that might look like:
<img width="1774" alt="image" src="https://github.com/user-attachments/assets/193df1dc-49c5-43e4-a673-d7d8b5289372">

<br><br>

Alternatively, we could simply include a table with field descriptions of the `subject_qc.csv` in the documentation similar to what we have for the `sample_qc.csv` at https://nci-cgr.github.io/GwasQcPipeline/sub_workflows/sample_qc.html#internal-sample-qc-report.

These changes will help us to better manage and analyze unexpected replicates.

**Comment by jaamarks** [comment]
It was decided in our meeting on 8/8/24 to retain the`is_unexpected_replicate` column while introducing a new column, `unexpected_replicate_status` for additional detail. The `is_unexpected_replicate` column will remain a boolean (True/False) to align with a downstream LIMS system. However, its value will change to False when a sample pair is contaminated, indicating an unexpected replicate with a contaminated counterpart. The `unexpected_replicate_status` column will use an integer scale as defined in the [above](https://github.com/NCI-CGR/GwasQcPipeline/issues/269#issuecomment-2273906441) GitHub comment.

Additionally, a separate data dictionary Excel file `QC_Report_Data_Dictionary.xlsx` will be created to accompany the `QC_Report.xlsx`. This new file will provide a dictionary for each sheet in the `QC_Report.xlsx`.

**Comment by jaamarks** [comment]
The following is a screenshot of the terminal's stdout which showcases the logic of this new approach, while retaining `is_unexpected_replicate`: 

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/2b90d622-cdba-4c84-9b19-49a035d3d869">

<br><br>


`unexpected_replicate_status` values:
**0:** Not an unexpected replicate
**1:** Retained unexpected replicate (only the other sample is contaminated)
**2:** Not retained unexpected replicate (this sample is contaminated)
**3:** Not retained unexpected replicate (neither sample is contaminated)

**Comment by jaamarks** [comment]
# Testing the New Implementation

To validate the updated logic, we modified the sample_qc.csv file for subject I-0002601358, which is part of an unexpected replicate pair with subject I-0002616978. Both subjects were previously recorded as uncontaminated; however, to test the new logic, we altered the data for I-0002601358 to indicate that it is contaminated (`is_contaminated=True`)." Specifically, we made the following changes:

```
# Modified columns
analytic_exclusion: True
num_analytic_exclusion: 1
analytic_exclusion_reason: Contamination
is_subject_representative: False
is_contaminated: True
```

After running the `subject_qc` and `delivery` sub-workflows, we compared the results in `QC_Report.xlsx` and in `QC_Report.docx` with those from the previous implementation.

**Expected Results:**

* Column D (`Unexpected Replicate`) in the`SUBJECT_QC` sheet of `QC_Report.xlsx` should reflect the updated status. Specifically, the status of subject `I-0002616978` should change to indicate that it is no longer an unexpected replicate.
* The counts in Tables 4a and 4b in `QC_Report.docx` should also align with the expected changes.

<br><br>

## SUBJECT_QC column D comparison
| Previous                                                                                                            | New                                                                                                                 |
|---------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|
| <img width="807" alt="image" src="https://github.com/user-attachments/assets/bc0d5c62-c4d3-434a-b0c0-f656e57c300a"> | <img width="902" alt="image" src="https://github.com/user-attachments/assets/ba226984-bce6-4f61-b8ee-3664a0600951"> |

<br>

## Table 4a and 4b comparison
| Previous                                                                                                            | New                                                                                                                 |
|---------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|
| <img width="930" alt="image" src="https://github.com/user-attachments/assets/a4de47fb-411a-41e1-be09-fb216f890072"> | <img width="936" alt="image" src="https://github.com/user-attachments/assets/77132de5-89e5-4582-b4de-6d72c1150ed4"> |

**Comment by jaamarks** [comment]
We noticed an issue when `is_contaminated=NA`. This should be handled in the `subject_qc_table.py` script.

**Comment by jaamarks** [comment]
Reopening due to #352.

Also, we noticed that `unexpected_replicate_status` showing up in the `QC_Report.xlsx`.
