### ISSUE TITLE
Ancestry = "Unknown" not shown in Table 3 Subject Counts by Ancestry Group

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#281]

**Comment by 1teaspoon** [comment]
ancestry assignment by graf-pop

**Comment by 1teaspoon** [comment]
"Other" needs to be populated in sample_qc.csv so that subject_qc.csv have this ancestry info and the pca and hwe plots will be generated for this  ancestry group.

**Comment by carynwillis** [comment]
Closing as a duplicate of issue #326 which has been completed and closed.
