### ISSUE TITLE
dynamically adjust minimum MAF for HWE calculation and add option to set HWE p value threshold

### ISSUE THREAD

**Issue by shukwong** [NCI-CGR/GwasQcPipeline#287]
Currently, the MAF for HWE is set for all ancestries groups, but a larger sample size could allow lower MAF.
We would like:
Within each ancestry x platform group, flag SNPs with [MAF > sqrt(5/n) & HWE-p<p-val-threshold] for exclusion, where n=number of controls in that ancestry x platform group

**Comment by kliao12** [comment]
@shukwong Do you have a reference for using sqrt(5/n) as the MAF cutoff that we can include in the docs or report?

**Comment by shukwong** [comment]
No reference. But the idea is that we will expect  >=5 alternative homozygous samples using sqrt(5/n) as a cutoff for MAF.
