### ISSUE TITLE
skip merging Graf, King and Plink results to make the QC pipeline more efficient 

### ISSUE THREAD

**Issue by shukwong** [NCI-CGR/GwasQcPipeline#302]
currently, the step (sample_concordance_summary?) takes >24 hours for 90k sample QC run because it needs to merge Graf, King, and Plink results. Graf and King relatedness results are not used downstream. We could skip merging these results. The Plink results will still be needed to estimate duplicates and close relatives.

**Comment by carynwillis** [comment]
For all sample sizes, we will instead output the Graf and King results separately instead of merging them with the Plink results.
