### ISSUE TITLE
high call rate chrY snps observed in genome studio are not retained in qc'ed genotype data

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#308]
We observed none chrY snps were retained in delivery/subjects.fam 
However we also observed at least 1000 snps have very good clustering and call rate in genome studio

**Comment by carynwillis** [comment]
I have confirmed the ChrY (Chr 24 in Plink)snps are in the pre-QC'd sample level plink files (sample_level/samples.bim) but are not in delivery/subjects.bim. I will look into where these snps are being dropped.
