### ISSUE TITLE
GTC to VCF creating too large of file for 100K+ samples

### ISSUE THREAD

**Issue by carynwillis** [NCI-CGR/GwasQcPipeline#318]
The new GTC to VCF step takes a long time if running on a large sample size and creates a very large (1TB+) vcf file. Will attempt to reduce file size by writing to a bcf instead of vcf.

**Comment by carynwillis** [comment]
Closing as this was fixed with the bcf conversion implementation #346.

**Comment by jaamarks** [comment]
Also see #346 which adds option to convert GTC-BCF
