### ISSUE TITLE
Profile per sample rules

### ISSUE THREAD

**Issue by jfear** [NCI-CGR/GwasQcPipeline#67]
I need to memory profile per sample rules to figure out what is the optimal mem_gb to set.

**Comment by bballew** [comment]
Hey @jfear your sge profile is fire.  What are you thinking of doing to allocate memory?  Can you use `-l h_vmem=` on the cluster?

**Comment by jfear** [comment]
@bballew hahaha, I ended up using `-l mem_free=` which runs, but I am not convinced it does anything. Mostly, I wanted to maintain consistency between the cgems and biowulf profiles.
